name: Creating TranslationToSource Executables

on:
  push:
    branches:
      - build-testing
    # paths:
    #   - 'Created Tools & Other Scripts/TranslationToSource/**'

jobs:

  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: ["win-x64", "linux-x64", "osx-x64", "linux-arm64", "linux-arm", "osx-arm64"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Wait for other dev builds
      uses: softprops/turnstyle@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - name: Publish TranslationToSource
      run: |
        dotnet publish "./Created Tools & Other Scripts/TranslationToSource/TranslationToSource/TranslationToSource.csproj" --output ./dist --configuration Release -r ${{matrix.runtime}} 

        rm ./dist/*.pdb

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TranslationSource-${{matrix.runtime}}
        path: ./dist/TranslationToSource*

  Create_Release:
    needs: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Get Version
      run:  |
        grepVersion=$(grep -oPm1 "(?<=<Version>)[^<]+" './Created Tools & Other Scripts/TranslationToSource/TranslationToSource/TranslationToSource.csproj')
        echo "version=$grepVersion" >> $GITHUB_ENV

        echo $grepVersion

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{env.version}}
        name: Building Exes for TranslationToSource
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}